name: regtest
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  boltz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Setup Regtest
        run: |
          cd docker
          chmod +x ./regtest
          ./regtest
      - name: Install dependencies
        run: |
          uv sync --locked --dev
      - name: Run tests
        run: |
          uv run pytest
